package ch.admin.foitt.wallet.platform.utils

enum class TestTags {

    CONTINUE_BUTTON,
    START_BUTTON,
    BACK_BUTTON,
    ACCEPT_BUTTON,
    DECLINE_BUTTON,
    ERROR,
    TO_SETTING_BUTTON,
    NO_BIOMETRICS_BUTTON,
    MENU_BUTTON,
    LOADING_ICON,

    // Onboarding Icons
    INTRO_ICON,
    PRESENT_ICON,
    LOCAL_DATA_ICON,
    USER_PRIVACY_ICON,
    PIN_EXPLANATION_ICON,
    BIOMETRICS_UNAVAILABLE_ICON,
    SUCCESS_ICON,

    // Home screen
    NO_CREDENTIAL_ICON,
    SCAN_TEXT_BUTTON,

    // Pin
    TOP_BAR_TITLE,
    PIN_FIELD,
    SHOW_PASSPHRASE_ICON,
}
